//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.SubmitIdea.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.SubmitIdea.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zihni Sinir Fikirler.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerikleri Etiket, Tür, ve Önerilere göre &lt;b&gt;keşfedin&lt;/b&gt; ve ilgi alanınızda en yeni çıkanlar ya da Popülerliğe göre sıralayın. &lt;br /&gt;
        ///Şahsi listenize &lt;b&gt;içerik ekleyin&lt;/b&gt; öğrenmek ve kendinizi gelistirmek için daha sonra ziyaret edin. &lt;br /&gt;
        ///Sizi etkileyen veya ilham veren içeriği iş arkadaşlarınızla &lt;b&gt;paylaşın.&lt;/b&gt;.
        /// </summary>
        public static string CarouselCard1Text {
            get {
                return ResourceManager.GetString("CarouselCard1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konular hakkında güncel kalmak için bir kanala tercihinize göre eklenen bir &lt;b&gt; içerik özeti &lt;/b&gt; alın..
        /// </summary>
        public static string CarouselCard2Text {
            get {
                return ResourceManager.GetString("CarouselCard2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekibinizle birlikte öğrenmek için etiketlere göre Kanal Sekmesine &lt;b&gt; ekleyin &lt;/b&gt; {0}.&lt;br /&gt;
        ///En sevdiğiniz yazıları arkadaşlarınızın gelişmesine yardımcı olmak için bir kanalda veya sohbette &lt;b&gt; paylaşın &lt;/b&gt;..
        /// </summary>
        public static string CarouselCard3Text {
            get {
                return ResourceManager.GetString("CarouselCard3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string CategoryNameText {
            get {
                return ResourceManager.GetString("CategoryNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Kategori:**.
        /// </summary>
        public static string CategoryText {
            get {
                return ResourceManager.GetString("CategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Özeti ayarlayın.
        /// </summary>
        public static string ConfigureDigestBulletText {
            get {
                return ResourceManager.GetString("ConfigureDigestBulletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özeti ayarlayın.
        /// </summary>
        public static string ConfigureDigestButtonText {
            get {
                return ResourceManager.GetString("ConfigureDigestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zihni sinir bir fikir herkesten gelebilir değil mi? Haydi başlayalım!.
        /// </summary>
        public static string ContentText {
            get {
                return ResourceManager.GetString("ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba ben Zihni Sinir Fikirler botuyum ve herkesi fikir göndermeye ve oylamaya teşvik ederek kuruluşunuzun yenilik yapmasına yardımcı olmak için buradayım..
        /// </summary>
        public static string CuratorWelcomeCardContent {
            get {
                return ResourceManager.GetString("CuratorWelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip etmek istediğiniz sıklığı ve sekmeyi seçerek özet tercihlerinizi ayarlayabilirsiniz..
        /// </summary>
        public static string DigestPreferenceCardContent {
            get {
                return ResourceManager.GetString("DigestPreferenceCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha fazla konuyu veya farklı konuları ayarlayabilir ve ayrıca özetin ne sıklıkta gönderileceğini değiştirebilirsiniz..
        /// </summary>
        public static string DigestPreferenceCardHeaderText {
            get {
                return ResourceManager.GetString("DigestPreferenceCardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özet seçeneklerinizi ayarlayın.
        /// </summary>
        public static string DigestPreferenceTitleText {
            get {
                return ResourceManager.GetString("DigestPreferenceTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir şeyler yanlış gitti. Birkaç dakika sonra tekrar deneyin..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleyen.
        /// </summary>
        public static string IdeatorLabelText {
            get {
                return ResourceManager.GetString("IdeatorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmeyen kiracı kimliği bulundu..
        /// </summary>
        public static string InvalidTenantText {
            get {
                return ResourceManager.GetString("InvalidTenantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık özetiniz.
        /// </summary>
        public static string NotificationCardMonthlyTitleText {
            get {
                return ResourceManager.GetString("NotificationCardMonthlyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftalık özetiniz.
        /// </summary>
        public static string NotificationCardWeeklyTitleText {
            get {
                return ResourceManager.GetString("NotificationCardWeeklyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Bir fikir gönderin - Fikrinizi göndermenizi sağlar.
        /// </summary>
        public static string SubmitAnIdeaBulletPoint {
            get {
                return ResourceManager.GetString("SubmitAnIdeaBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fikir gönder.
        /// </summary>
        public static string SubmitAnIdeaButtonText {
            get {
                return ResourceManager.GetString("SubmitAnIdeaButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fikir gönder.
        /// </summary>
        public static string SubmitIdeaTitleText {
            get {
                return ResourceManager.GetString("SubmitIdeaTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketler.
        /// </summary>
        public static string TagsLabelText {
            get {
                return ResourceManager.GetString("TagsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zihni Sinir Fikirler.
        /// </summary>
        public static string TaskModuleTitleText {
            get {
                return ResourceManager.GetString("TaskModuleTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu komutu bilmiyorum. Şu komutlardan birini yazmayı deneyin:
        ///-Preferences , -Help.
        /// </summary>
        public static string UnsupportedBotCommandText {
            get {
                return ResourceManager.GetString("UnsupportedBotCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu komutu bilmiyorum..
        /// </summary>
        public static string UnsupportedBotPersonalCommandText {
            get {
                return ResourceManager.GetString("UnsupportedBotPersonalCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Tüm fikirler - Meslektaşlarınızın fikirlerini görüntülemenizi ve oy vermenizi sağlar.
        /// </summary>
        public static string ViewIdeaBulletPoint {
            get {
                return ResourceManager.GetString("ViewIdeaBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba ben Zihni Sinir Fikirler botuyum ve herkesi fikir göndermeye ve oylamaya teşvik ederek kuruluşunuzun yenilik yapmasına yardımcı olmak için buradayım..
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşte yazabileceğiniz komutlar ve yaptıkları:.
        /// </summary>
        public static string WelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("WelcomeSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba ben Zihni Sinir Fikirler botuyum ve herkesi fikir göndermeye ve oylamaya teşvik ederek kuruluşunuzun yenilik yapmasına yardımcı olmak için buradayım..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
    }
}
