//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.SubmitIdea
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.SubmitIdea.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Ideas.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Discover&lt;/b&gt; content by Tags, Type, Suggested by and sort by Popularity/latest based on your interest. &lt;br /&gt;
        ///&lt;b&gt;Add content&lt;/b&gt; to your private list and visit later to learn and grow.
        /// &lt;br /&gt;
        ///&lt;b&gt;Share&lt;/b&gt; content that influenced or inspired you with your co-workers..
        /// </summary>
        public static string CarouselCard1Text {
            get {
                return ResourceManager.GetString("CarouselCard1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a &lt;b&gt;digest of content&lt;/b&gt; that are added based on your preference in a channel to stay updated on the topics..
        /// </summary>
        public static string CarouselCard2Text {
            get {
                return ResourceManager.GetString("CarouselCard2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Add&lt;/b&gt; {0} to the Channel Tab based on tags to learn together with your team.
        ///&lt;br /&gt;
        ///&lt;b&gt;Share&lt;/b&gt; your favorite reads in a channel or chat to help your Peers grow..
        /// </summary>
        public static string CarouselCard3Text {
            get {
                return ResourceManager.GetString("CarouselCard3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Category:**.
        /// </summary>
        public static string CategoryText {
            get {
                return ResourceManager.GetString("CategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Configure digest.
        /// </summary>
        public static string ConfigureDigestBulletText {
            get {
                return ResourceManager.GetString("ConfigureDigestBulletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure digest.
        /// </summary>
        public static string ConfigureDigestButtonText {
            get {
                return ResourceManager.GetString("ConfigureDigestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A great idea can come from anyone, right? Let&apos;s get started!.
        /// </summary>
        public static string ContentText {
            get {
                return ResourceManager.GetString("ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Great Ideas bot, and I&apos;m here to help your org innovate by encouraging everyone to submit and vote on ideas..
        /// </summary>
        public static string CuratorWelcomeCardContent {
            get {
                return ResourceManager.GetString("CuratorWelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set digest preference by selecting the frequency and tab you wants to follow..
        /// </summary>
        public static string DigestPreferenceCardContent {
            get {
                return ResourceManager.GetString("DigestPreferenceCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can configure more topics or different ones as well as change how often the digest is posted..
        /// </summary>
        public static string DigestPreferenceCardHeaderText {
            get {
                return ResourceManager.GetString("DigestPreferenceCardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure digest settings.
        /// </summary>
        public static string DigestPreferenceTitleText {
            get {
                return ResourceManager.GetString("DigestPreferenceTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected tenant id found..
        /// </summary>
        public static string InvalidTenantText {
            get {
                return ResourceManager.GetString("InvalidTenantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your monthly digest.
        /// </summary>
        public static string NotificationCardMonthlyTitleText {
            get {
                return ResourceManager.GetString("NotificationCardMonthlyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weekly digest.
        /// </summary>
        public static string NotificationCardWeeklyTitleText {
            get {
                return ResourceManager.GetString("NotificationCardWeeklyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Submit an idea - Lets you submit your idea.
        /// </summary>
        public static string SubmitAnIdeaBulletPoint {
            get {
                return ResourceManager.GetString("SubmitAnIdeaBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit idea.
        /// </summary>
        public static string SubmitAnIdeaButtonText {
            get {
                return ResourceManager.GetString("SubmitAnIdeaButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit an idea.
        /// </summary>
        public static string SubmitIdeaTitleText {
            get {
                return ResourceManager.GetString("SubmitIdeaTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsLabelText {
            get {
                return ResourceManager.GetString("TagsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Ideas.
        /// </summary>
        public static string TaskModuleTitleText {
            get {
                return ResourceManager.GetString("TaskModuleTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that command. Try typing command:
        ///-Preferences , -Help.
        /// </summary>
        public static string UnsupportedBotCommandText {
            get {
                return ResourceManager.GetString("UnsupportedBotCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that command..
        /// </summary>
        public static string UnsupportedBotPersonalCommandText {
            get {
                return ResourceManager.GetString("UnsupportedBotPersonalCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * All ideas - Lets you view and upvote your colleagues&apos; ideas.
        /// </summary>
        public static string ViewIdeaBulletPoint {
            get {
                return ResourceManager.GetString("ViewIdeaBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Great Ideas bot, and I&apos;m here to help your org innovate by encouraging everyone to submit and vote on ideas..
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the commands you can type and what they do:.
        /// </summary>
        public static string WelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("WelcomeSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Great Ideas bot, and I&apos;m here to help your org innovate by encouraging everyone to submit and vote on ideas..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
    }
}
